repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: debug-statements
      - id: check-case-conflict
      - id: check-symlinks
      - id: mixed-line-ending

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        files: ^packages/backend/
      - id: ruff-format
        files: ^packages/backend/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        files: ^packages/backend/src/
        args: [--strict]
        # Add libraries that don't have inline types or stubs here
        additional_dependencies: [
        ]

-   repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        files: ^packages/backend/
        args: ["--quiet", "-x", "tests/"]

-   repo: https://github.com/jsh9/pydoclint
    rev: 0.6.7
    hooks:
      - id: pydoclint
        files: ^packages/backend/
        args: [--style=numpy, "--quiet"]
